config/routes.rb
PaymentApp::Application.routes.draw do

  resources :sessions
  resources :users
  resources :invoices
  resources :items
  
  
  
  get '/sign_up' => 'users#new'
  get '/sign_in' => 'sessions#new'
  get '/sign_out' => 'sessions#destroy'
  get '/paidlist' => 'invoices#paid'
  get '/pendinglist' => 'invoices#pending'
  
  get '/yourkey' => 'users#key'
  
  post '/paymentmade/:id' => 'invoices#payment_made'
  post '/paymentrevert/:id' => 'invoices#payment_revert'
  
  post '/chargeinvoice/:id' => 'invoices#charge_credit_invoice'
  
  get '/moreinvoices' => 'invoices#more_invoices'
  
  get '/morepaid' => 'invoices#more_paid'
  get '/morepending' => 'invoices#more_pending'
  
  

  root :to => 'landing#index'

end

app/views/layouts/_footer.haml
#footer
  %ul.left
    %li
      = link_to "about", "/about"
    %li
      = link_to "faq", "/faq"
    %li
      =link_to 'contact', ""
    %li.reset_border
      =link_to '@taazr', "http://twitter.com/cottonbot"
  %ul.right
    %li.copy.reset_border
      &copy; 2011 Taazr Corp.
    .clear
  .clear

app/views/layouts/_header.haml
#header
  #inner
    -if !current_user 
      #logo.left
        =link_to "Invoice", root_path
    -if current_user
      #nav_bar_landing.left
        %ul.top_nav_bar
          %li
            = link_to "New Invoice", new_invoice_path, :class => "new_invoice_link pressed_link"
          %li
            = link_to "Overview", invoices_path, :class => "overview_link"
          %li
            = link_to "Paid", "/paidlist", :class => "paid_link"
          %li
            = link_to "Pending", "/pendinglist", :class => "pending_link"
    #auth_right.right
      -if current_user
        %ul
          %li= link_to "Sign Out", '/sign_out'
      -else
        %ul
          %li=link_to 'Sign up', new_user_path
          %li= link_to "Sign In", '/sign_in'
    .clear

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaymentApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/header' %>
  <%= yield %>
  <%= render '/layouts/footer' %>
</body>
</html>